"""Initial migration

Revision ID: 001666b7782d
Revises: 
Create Date: 2025-01-11 10:57:36.471761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001666b7782d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event', type_='foreignkey')
        batch_op.drop_constraint('fk_attendee', type_='foreignkey')
        batch_op.create_foreign_key(None, 'attendees', ['attendee_id'], ['id'])
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'])

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event', type_='foreignkey')
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_event', 'events', ['event_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_attendee', 'attendees', ['attendee_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_event', 'events', ['event_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
